### ISSUE TITLE
MeV fails to start

### ISSUE THREAD

**Issue by drcouzelis** [HaikuArchives/MeV#3]
After installing MeV from the HaikuDepot and clicking on the application icon in the "Applications" menu, a popup appears with the text:

> There was an error resolving the link.

**Comment by waddlesplash** [comment]
This is a problem with the recipe.

**Comment by korli** [comment]
I tried to build on gcc2, it's broken since "BLocker: Make copy constructor & assignment operator private." https://github.com/haiku/haiku/commit/69b8f7f1f4d66896245d1e10df00144e3b78e602

**Comment by waddlesplash** [comment]
https://github.com/HaikuArchives/MeV/commit/8cc79bc699b8ef543535f3ea6367e399d0dd20f3
